/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javatechnics_rs232_Serial */

#ifndef _Included_com_javatechnics_rs232_Serial
#define _Included_com_javatechnics_rs232_Serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    getNativeLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_javatechnics_rs232_Serial_getNativeLibraryVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    openSerialPort
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_openSerialPort
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    closeSerialPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_closeSerialPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    setNativeTerminalAttributes
 * Signature: (IILcom/javatechnics/rs232/TermIOS;)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_setNativeTerminalAttributes
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    getNativeTerminalAttributes
 * Signature: (I)Lcom/javatechnics/rs232/TermIOS;
 */
JNIEXPORT jobject JNICALL Java_com_javatechnics_rs232_Serial_getNativeTerminalAttributes
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    getNativeModemControlBits
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_getNativeModemControlBits
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    setNativeModemcontrolBits
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_setNativeModemcontrolBits
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    nativeTCFlush
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_nativeTCFlush
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    nativeTestRead
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_Serial_nativeTestRead
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
