/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javatechnics_rs232_stream_SerialPortInputStream */

#ifndef _Included_com_javatechnics_rs232_stream_SerialPortInputStream
#define _Included_com_javatechnics_rs232_stream_SerialPortInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_javatechnics_rs232_stream_SerialPortInputStream_MAX_SKIP_BUFFER_SIZE
#define com_javatechnics_rs232_stream_SerialPortInputStream_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     com_javatechnics_rs232_stream_SerialPortInputStream
 * Method:    readNative
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_javatechnics_rs232_stream_SerialPortInputStream_readNative
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
