/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javatechnics_rs232_stream_SerialPortOutputStream */

#ifndef _Included_com_javatechnics_rs232_stream_SerialPortOutputStream
#define _Included_com_javatechnics_rs232_stream_SerialPortOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javatechnics_rs232_stream_SerialPortOutputStream
 * Method:    nativeWrite
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_javatechnics_rs232_stream_SerialPortOutputStream_nativeWrite
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
