/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javatechnics_rs232_Serial */

#ifndef _Included_com_javatechnics_rs232_Serial
#define _Included_com_javatechnics_rs232_Serial
#ifdef __cplusplus
extern "C" {
#endif
#undef com_javatechnics_rs232_Serial_MAX_SKIP_BUFFER_SIZE
#define com_javatechnics_rs232_Serial_MAX_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     com_javatechnics_rs232_Serial
 * Method:    getNativeLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_javatechnics_rs232_Serial_getNativeLibraryVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
